### ISSUE TITLE
Iterate all values method feature?

### ISSUE THREAD

**Issue by cxj** [MJPA/SimpleJSON#22]
When one knows the keys of all the values in a JSON string, or the number of keys is small, using the JSONObject::find("some_key") method is a good way to retrieve values of interest.

I face a situation where I have a large JSON string with many keys, but not all will be present at any given time -- it's sparse and unpredictable data.

it would be easier and more efficient if instead of looping through a list of all possible keys and ::find()ing them, if I could instead iterate through the keys which exist in the JSON string.  For me, at least, order is not critical, so the potential free structure of the JSON object could be walked in any order, i.e. simple iterator loop with recursion.

Would the author consider adding such a method to this library, or accept a pull request which adds it?

**Comment by MJPA** [comment]
Ok, I've finally got round to this and added a `ObjectKeys()` method to the `JSONValue` class that will return a `std::vector<std::wstring>` containing the keys. It will be empty if the value is not an object.

To keep things simple, it will only give you the keys for the top most level.

Relevant commit is 339de6c6b6f00ab26d30cf5b0ef541036cd7fd37.
