### ISSUE TITLE
Add some more documentation to README

### ISSUE THREAD

**Issue by cdeil** [MJPA/SimpleJSON#23]
Could you please add some documentation to the README?

It currently says:

> The library consists of 2 classes - JSON and JSONValue.

but looking at the example https://github.com/MJPA/SimpleJSON/blob/master/src/demo/example.cpp#L120 it looks like there are `JSONObject` and `JSONArray` classes that can be used to generate JSON programatically, which is just what I need.

If you don't have time to write docs, maybe just say "go look at these example files" in the README?

**Comment by MJPA** [comment]
They're not really classes, the `JSONObject` is just a shorthand for a `std::map<std::wstring, JSONValue*>` and `JSONArray` is a shorthand for `std::vector<JSONValue*>`.

I will update the documentation to mention this though!
